spring.application.name=CampShare
# Nama Database: campushare_db (Pastikan teman DB Admin sudah membuat ini di phpMyAdmin)
spring.datasource.url=jdbc:mysql://localhost:3306/campushare_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Konfigurasi JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- KONFIGURASI EMAIL OTP ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aristria91@gmail.com
spring.mail.password=mkpikosxkpdfnjvf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.localhost=localhost